---
- name: Register docker-compose Stat
  stat:
    path: "{{ rocketchat_folder }}"
  register: stat_result

- name: Cat file if exists
  shell: "cat {{ rocketchat_folder }}/docker-compose.yml" 
  when: stat_result.stat.exists

- name: copy Docker Compose files
  become: true
  template:
    src: docker-compose.yml.j2
    dest: "{{ rocketchat_folder }}"
    mode: 0700
  tags: rocketchat
  when: stat_result.stat.exists

- name: Copy rocketchat update executable
  copy:
    src: "rocketchat_update.sh"
    dest: "/usr/local/bin/"
    mode: "0700"

- name: Update rocketchat script
  shell:
    cmd: "sh /usr/local/bin/rocketchat_update.sh -f {{ rocketchat_folder }} -v {{ rocketchat_configs.rocketchat_version }}"